### ISSUE TITLE
Cant Package My Windows Build

### ISSUE THREAD

**Issue by khushiloneknotone** [IamKingWaiMark/FBP#17]
Hello, When I am trying to package my Windows build in UE 5.2, it displays an Error stating LNK 2001: unresolved external symbol of your plugin.
Please Help.
Below shows Log Details:
UATHelper: Packaging (Windows):    Creating library C:\X\Malabar_Retreat\Binaries\Win64\Malabar.lib and object C:\X\Malabar_Retreat\Binaries\Win64\Malabar.exp
UATHelper: Packaging (Windows): firebase_database.lib(114ee88c147ee2a19e092215047fd9a9_libuWS.dir_Release_WebSocket.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_database.lib(114ee88c147ee2a19e092215047fd9a9_libuWS.dir_Release_Hub.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_firestore.lib(060e08416dfaa8337f6db6660c103cb2_firestore_core.dir_Release_grpc_connection.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_storage.lib(ec8e84d87ed30ad4d45497f650aa581b_firebase_storage.dir_Release_storage_desktop.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_database.lib(114ee88c147ee2a19e092215047fd9a9_libuWS.dir_Release_Group.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_database.lib(cac87a85652b62435795dae46530cd28_firebase_database.dir_Release_web_socket_client_impl.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_database.lib(114ee88c147ee2a19e092215047fd9a9_libuWS.dir_Release_Networking.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_database.lib(114ee88c147ee2a19e092215047fd9a9_libuWS.dir_Release_HTTPSocket.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_database.lib(cac87a85652b62435795dae46530cd28_firebase_database.dir_Release_write_tree.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_database.lib(cac87a85652b62435795dae46530cd28_firebase_database.dir_Release_connection.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_database.lib(cac87a85652b62435795dae46530cd28_firebase_database.dir_Release_util_connection.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_database.lib(114ee88c147ee2a19e092215047fd9a9_libuWS.dir_Release_Node.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_app.lib(9517b511b2df07341741fe8d83119943_firebase_app.dir_Release_cleanup_notifier.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_app.lib(9df1b499e9d93fa7bea97ae713d33ce7_flatbuffers.dir_Release_idl_parser.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_auth.lib(d48c2d5c2ee6ee6849b2a8e761eb596c_firebase_auth.dir_Release_auth.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_database.lib(cac87a85652b62435795dae46530cd28_firebase_database.dir_Release_database_desktop.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
UATHelper: Packaging (Windows): firebase_firestore.lib(1fe95d6838d9909cdf909015eeba18ea_re2.dir_Release_stringpiece.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1
UATHelper: Packaging (Windows): firebase_app.lib(9517b511b2df07341741fe8d83119943_firebase_app.dir_Release_heartbeat_storage_desktop.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1
UATHelper: Packaging (Windows): firebase_firestore.lib(ec49100c7e8ab9d550bace2974e79db6_firestore_util.dir_Release_string_format.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1
UATHelper: Packaging (Windows): firebase_firestore.lib(eb538fd19dcffbedfd665e1dfbbc15d8_absl_str_format_internal.dir_Release_arg.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1
UATHelper: Packaging (Windows): firebase_firestore.lib(f629d927b3c258f787fa088466975c44_absl_strings.dir_Release_charconv_bigint.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1
UATHelper: Packaging (Windows): firebase_firestore.lib(1fe95d6838d9909cdf909015eeba18ea_re2.dir_Release_re2.obj) : error LNK2019: unresolved external symbol __std_init_once_link_alternate_names_and_abort referenced in function "public: __cdecl std::_Init_once_completer::~_Init_once_completer(void)" (??1_Init_once_completer@std@@QEAA@XZ)
UATHelper: Packaging (Windows): firebase_firestore.lib(1fe95d6838d9909cdf909015eeba18ea_re2.dir_Release_dfa.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort
UATHelper: Packaging (Windows): firebase_firestore.lib(1fe95d6838d9909cdf909015eeba18ea_re2.dir_Release_regexp.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort
UATHelper: Packaging (Windows): C:\X\Malabar_Retreat\Binaries\Win64\Malabar.exe : fatal error LNK1120: 3 unresolved externals
UATHelper: Packaging (Windows): [2/2] WriteMetadata Malabar.target cancelled
UATHelper: Packaging (Windows): Took 5.4455909s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\Khushil\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.2\UBT-Malabar-Win64-Development.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 6s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by NonLocalityDev** [comment]
I have this exact issue too, any update??
